#!/bin/bash

for number in $(seq $1 $2)
do
	if [ $(($number % 15)) -eq 0 ] 
		then echo "$number : FooBar"
	elif [ $(($number % 5)) -eq 0 ]
		then echo "$number : Bar"
	elif [ $(($number % 3)) -eq 0 ]
		then echo "$number : Foo"
	else
		echo "$number : N/A"
	fi
done

