#!/bin/bash

n=$1

dirname="$2"

shift 2

read -p "Enter text to send: " txt

outfile="active_users_under_file_threshold"
> "$outfile"

for user in $*; do
	if who | grep -q "^$user "; then
		if [ -d "$dirname"/"$user" ]; then
			filecount=$(find "$dirname"/"$user" -maxdepth 1 -type f | wc -l)
			if [ $filecount -gt $n ]; then
				echo "$txt" | write "$user"
			else
				echo "$user has $filecount files in the directory $dirname/$user" >> "$outfile"
			fi
		fi
	fi
done

sort -o "$outfile" "$outfile"
